import { StyleSheet, Dimensions } from 'react-native';
import { COLOR, FONTSIZE, NUMBER, CONSTANT } from '../../utils/constant';

const { height, width } = Dimensions.get('window');

const headerLogoRatio = 287 / 150;
const headerLogoWidth = width * 0.25;
const headerLogoHeight = headerLogoWidth / headerLogoRatio;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: COLOR.WHITE,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width,
    height: height * 0.12,
    backgroundColor: COLOR.BACKGROUND,
  },
  logo: {
    alignSelf: 'center',
    marginTop: height * 0.025,
    width: headerLogoWidth,
    height: headerLogoHeight,
  },
  title: {
    marginTop: CONSTANT.title_margin_top,
    marginLeft: '5%',
    width: '90%',
    height: CONSTANT.text_height,
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: FONTSIZE.title_size,
  },
  // Find verhicle Form
  findVerhicleForm: {
    flexDirection: 'column',
    marginTop: height * 0.03,
    marginLeft: '5%',
    width: '90%',
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: COLOR.GREY_2,
  },
  headerform: {
    position: 'absolute',
    left: 0,
    top: 0,
    flexDirection: 'row',
    width: '100%',
    height: height * 0.075,
    backgroundColor: COLOR.GREY,
  },
  iconHeader: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '15%',
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLOR.BUTTON_COLOR,
  },
  toggle_arrow: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  titleForm: {
    flex: 1,
    textAlign: 'center',
    textAlignVertical: 'center',
    height: '100%',
    color: COLOR.BACKGROUND,
    fontWeight: 'bold',
    fontSize: FONTSIZE.title_form_size
  },
  contentForm: {
    flex: 0.85,
    marginTop: height * 0.075,
    flexDirection: 'column',
    paddingTop: '3.61%',
  },
  inputField: {
    borderRadius: 8,
    marginLeft: '7.5%',
    marginRight: '7.5%',
    marginTop: '3.53%',
    paddingLeft: '5%',
    paddingRight: '5%',
    width: '85%',
    height: height * 0.075,
    backgroundColor: COLOR.BACKGROUND,
  },
  selectViewGroup: {
    paddingLeft: '7.5%',
    paddingRight: '7.5%',
    marginTop: '3.53%',
    width: '100%',
    borderRadius: 8,
  },
  selectField: {
    borderRadius: 8,
    height: height * 0.075,
    backgroundColor: COLOR.BACKGROUND,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    flexDirection: 'column',
    justifyContent: 'center',
    borderRadius: 8,
    marginLeft: '7.5%',
    marginRight: '7.5%',
    marginTop: '5.3%',
    width: '85%',
    height: height * 0.075,
    backgroundColor: COLOR.BUTTON_COLOR,
  },
  buttonLabel: {
    alignSelf: 'center',
    paddingTop: height * 0.01875,
    color: COLOR.BACKGROUND,
    width: '100%',
    height: '100%',
    textAlign: 'center',
    fontSize: FONTSIZE.button_label_size,
  },
  findPricingForm: {
    flexDirection: 'column',
    marginTop: height * 0.03,
    marginLeft: '5%',
    width: '90%',
    height: height * 0.578125,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: COLOR.GREY_2,
  },
  findPricingField: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: '7.5%',
    marginRight: '7.5%',
    height: height * 0.075,
    width: '85%',
  },
  labelFindPricing: {
    color: COLOR.BUTTON_COLOR,
    textAlignVertical: 'center',
    width: '40%',
    fontSize: FONTSIZE.find_pricing_label_size,
  },
  valueFindPricing: {
    color: COLOR.BLACK,
    textAlignVertical: 'center',
    width: '60%',
    fontSize: FONTSIZE.find_pricing_label_size,
  },
  selectGlassTypeGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: '7.5%',
    marginRight: '7.5%',
    width: '85%',
    height: height * 0.075,
  },
  labelSelect: {
    textAlignVertical: 'center',
    fontSize: FONTSIZE.button_label_size,
    height: height * 0.075,
  },
  selectGlassTypeField: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLOR.BACKGROUND,
    width: '100%',
    borderRadius: 8,
    height: height * 0.075,
  },
  finalizeForm: {
    flexDirection: 'column',
    marginTop: height * 0.03,
    marginBottom: height * 0.03,
    marginLeft: '5%',
    width: '90%',
    height: height * 0.578125,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: COLOR.GREY_2,
  },
  groupMarkedPrice: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginLeft: '7.5%',
    marginRight: '7.5%',
    width: '85%',
    marginBottom: height * 0.03,
    height: height * 0.2,
  },
  priceMarkupButton: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '45%',
    borderRadius: 8,
    height: height * 0.1,
  },
  priceMarkupLabelButton: {
    color: COLOR.BACKGROUND,
    fontSize: 19,
    textAlign: 'center',
    marginBottom: '2.5%',
  },
  priceOtherAmount: {
    width: '45%',
    borderRadius: 8,
    height: height * 0.1,
    textAlign: 'center',
    fontSize: 19,
  },
  overlays: {
    position: 'absolute',
    width: width,
    height: height,
    backgroundColor: COLOR.GREY_SUBTRAST,
  },

});

export default styles;
